config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :users, only: [:show]
  resources :locations do
    resources :events, only: [:new, :create]
  end
  resources :events, only: [:index, :show, :edit, :update, :destroy] do
    resources :event_participants, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location
  belongs_to :user
  has_many :event_participants, dependent: :destroy
  has_many :users, through: :event_participants
  # validates :name, presence: true
  validates :schedule, presence: true
  validates :location, presence: true, uniqueness: true
end

app/models/event_participant.rb
class EventParticipant < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/location.rb
class Location < ApplicationRecord
  GARBAGE = ['Verre', 'Emballage et plastique', 'Textile', 'Ordures ménagères', 'Métal', 'Déchets industriels', 'Électroménager']

  belongs_to :user
  has_one :event, dependent: :destroy
  validates :name, presence: true
  validates :longitude, presence: true
  validates :latitude, presence: true
  mount_uploader :photo, PhotoUploader
  # validates :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:google_oauth2]
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :locations, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :event_participants, dependent: :destroy

  validates :email, presence: true
  validates :password, presence: true
  validates :username, presence: true

  after_create :send_welcome_email

  def self.from_omniauth(access_token)
      data = access_token.info
      user = User.where(email: data['email']).first

      # Uncomment the section below if you want users to be created if they don't exist
      unless user
          user = User.create(
            username: data['name'],
            email: data['email'],
            password: Devise.friendly_token[0,20]
             # remote_avatar_url: access_token['info']['image']
          )
      end
      user
  end

  def password_required?
    false
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
    # locations_path
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
    # locations_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  private
  # Its important that the location is NOT stored if:
  # - The request method is not GET (non idempotent)
  # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
  #    infinite redirect loop.
  # - The request is an Ajax request as this can lead to very unexpected behaviour.
  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/event_participants_controller.rb
class EventParticipantsController < ApplicationController
  def create
    @event_participant = EventParticipant.new
    @event = Event.find(params[:event_id])
    @event_participant.event = @event
    @event_participant.user = current_user
    if @event_participant.save
      # CHANGER LA REDIRECTION
      redirect_to event_path(@event)
    else
      redirect_to event_path(@event), notice: 'Failure'
    end
  end

  def destroy
    # à simplifier en ne faisant pas une nested route
    @event = Event.find(params[:event_id])
    @event_participant = EventParticipant.find_by(user: current_user, event: @event)
    @event_participant.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to event_path(@event_participant.event)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @location = Location.find(params[:location_id])
  end

  def create
    @event = Event.new(event_params)
    @location = Location.find(params[:location_id])
    @event.location = @location
    @event.user = current_user

    if @event.save
      @event_participant = EventParticipant.create(user: current_user, event: @event)
      redirect_to event_path(@event), notice: 'Collecte créée !'
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :schedule)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @locations = Location.where.not(latitude: nil, longitude: nil)
    @markers = @locations.map do |location|
          {
            long: location.longitude,
            lat: location.latitude,
            image_url: helpers.asset_url('newcurseurmap.png'),
            infoWindow: render_to_string(partial: "infowindow", locals: { location: location })
          }
    end
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.longitude = params[:long]
    @location.latitude = params[:lat]
    @location.user = current_user
    if @location.save
      redirect_to locations_path, notice: 'Décharge signalée !'
    else
      render :new
    end
  end

  def show
    @location = Location.find(params[:id])
    # @location.garbage.shift # à régler : le premier string de l'array est vide // input hidden ?
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def location_params
    params.require(:location).permit(:name, :description, :lat, :long, :photo, garbage:[])
    # bien rajouter :[] à la colmun qui est un array
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all
    users_scores = @users.map do |user|
      user.events.count + user.event_participants.count
    end
    # début de la solution correcte
    # users_scores = @users.map do |user|
    #   if user.points
    #     user.points
    #   else
    #     0
    #   end
    # end
    ordered_users_scores = users_scores.sort.reverse
    @user_points = @user.events.count + @user.event_participants.count
    @rank = ordered_users_scores.index(@user_points) + 1
  end

  # def update
  #   @user = User.find(params[:id])
  #   @user.update_attribute(:username, user_params[:username])

  #   redirect_to user_path
  # end

  # private

  #   def user_params
  #     params.require(:user).permit(:username)
  #   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= simple_form_for [@location, @event] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.input :schedule, label: 'Date et heure de début', as: :string, start_year: Date.today.year, end_year: Date.today.year + 2, order: [:day, :month, :year] %>
  <%= f.submit "Créer", class: "btn btn-block btn-lieu" %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="lesevents">
  <h1>Liste des collectes</h1>
  <% @events.each do |event| %>
    <div class="card la" >
      <div class="card-img-top">
        <%= cl_image_tag event.location.photo, height: 200, width: 300, crop: :fill %>
      </div>
      <div class="card-body bodycard">
        <h4 class="card-title"><i class="fas fa-map-marked-alt i"></i><%= event.location.name %></h4>
        <p class="card-text"><i class="far fa-calendar-alt i"></i><%= l(event.schedule, format: '%A %e %B %Y') %></p>

        <!-- <a href="#" class="btn center-block btn-success"></i>Voir l'événement</a> -->
        <%= link_to 'Voir la collecte', event_path(event), class: "btn center-block" %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="nouveleve">
  <h1> Organiser une nouvelle collecte </h1>
  <h2> Lieu : <%= @location.name %> </h2>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>
<!-- <h3> Date </h3>
<h4> Heure de début </h4>
<h4> Heure de fin </h4> -->

app/views/events/show.html.erb
<div class="rejoindre">

  <h1> Rejoindre la collecte </h1>

  <div class="bodyrejoindre">
    <h2> <%= @event.location.name %>
    <h4> <%= l(@event.schedule, format: '%A %e %B %Y %H:%M') %> </h4>
    <% if @event.user == current_user  %>
      <h6 style="text-align: center"> <em> Collecte créée par vous </em> </h6>
    <% else %>
      <h6 style="text-align: center"> <em> Collecte créée par <%= @event.user.username %> </em> </h6>
    <% end %>
  </div>


  <br>

  <% if @event.event_participants.length == 0 %>
    <p> Pas encore de participant à cette collecte </p>
  <% elsif @event.event_participants.length == 1 %>
    <p> <%= @event.event_participants.length %> participant à cette collecte </p>
  <% else %>
    <p> <%= @event.event_participants.length %> participants à cette collecte </p>
  <% end %>


    <% if @event.users.include?(current_user)  %>
      <p>
        <i class="fa fa-check" aria-hidden="true"></i> Vous participez à cette collecte
      </p>
      <p> <%= link_to 'Se désinscrire', event_event_participant_path(@event), class: "btn btn-danger", method: :delete  %>
    <% else %>
      <p>
        <%= link_to 'Participez à cette collecte', event_event_participants_path(@event), class: "btn btn-lieu", method: :post  %>
      </p>
    <% end %>


  <div class="socials" style="display: flex">
    <div id="fb-root"></div>
    <script async defer src="https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v3.2&appId=414892035984987&autoLogAppEvents=1"></script>

    <div class="fb-share-button" data-href="https://green-up.herokuapp.com/" data-layout="button" data-size="large" data-mobile-iframe="true" style="margin-right: 15px"><a target="_top" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Ftoto.com%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Partager</a></div>

    <script>window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);

      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };

      return t;
    }(document, "script", "twitter-wjs"));
    </script>

    <a class="twitter-share-button"
      href="https://twitter.com/intent/tweet?text=Hey%20les%20gars%20ça%20vous%20dit%20de%20venir%20nettoyer%20cet%20endroit%20avec%20moi"
      data-size="large">
    Tweet</a>
  </div>
</div>



<!--
SHOW Page d'évent : bouton partager Twitter / Fb, participer/se désinscrire, nb et liste des participants, organisateur, photo, date et heure (début et fin) -->

<!--
<p> Current user : <%= current_user.username %> (id : <%= current_user.id  %>) </p>
<p> Créateur de l'event : <%= @event.user.username %> (id : <%= @event.user_id %>) </p>
-->

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Green Up - pour une nature sans déchets </title>
    <!-- Pour progressive web app -->
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="apple-touch-startup-image" href="/logo.jpg">
    <link rel="apple-touch-icon" sizes="180x180" href="/logo.jpg">
    <link rel="manifest" href="manifest.json" >
    <link rel="pwa-setup" href="manifest.json">
    <script src="https://github.com/GoogleChromeLabs/pwacompat/blob/master/pwacompat.js"></script><link rel="manifest" href="manifest.json">
    <script>
       var iOS = !!navigator.platform && /iPhone|iPod/.test(navigator.platform);
       if(iOS) {
          document.querySelector('link[rel="manifest"]').setAttribute("rel", "no-on-ios");
       }
    </script>
    <!-- Meta Open Graph -->
    <meta property="og:title" content="Green Up, pour une nature sans déchets" />
    <meta property="og:description" content="Se réunir pour localiser et aller nettoyer les décharges sauvages" />
    <meta property="og:url" content="https://green-up.herokuapp.com/" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="<%= image_url 'logofb.jpg' %>" />
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- NE PAS OUBLIER -->
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v3.1.2/mapbox-gl-geocoder.min.js'></script>
    <link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v3.1.2/mapbox-gl-geocoder.css' type='text/css' />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,500,600,700" rel="stylesheet">
    <%= favicon_link_tag asset_path('logonew.png') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <div class="main-container">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for @location do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.input :name, label: "Nom de l'emplacement", placeholder: "Soyez le plus précis possible" %>
  <%= f.input :description, placeholder: "Prendre des gants..."%>
  <h3>Sélectionner les déchets présents</h3>
  <div class="checkboxinput">
    <div class="container">
      <ul class="ks-cboxtags">
        <% Location::GARBAGE.each_with_index do |garbage, i| %>
          <li>
            <input type="checkbox" id="checkbox<%= i %>" value="<%= garbage %>" name="location[garbage][]">
            <label for="checkbox<%= i %>"><%= garbage %></label>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="buttonphoto">
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <input type="hidden" name="lat" id="lat">
      <input type="hidden" name="long" id="long">
  </div>

  </div>

<div class="creer">
    <%= f.submit "Signaler cette décharge", class: "btn btn-block btn-lieu" %>
  <% end %>
</div>

app/views/locations/_infowindow.html.erb
<% if !location.photo.blank? %>

  <%= link_to location_path(location) do %>
    <div class="image-div" style="background-image: url(<%= cl_image_path(location.photo) %>)"> </div>
    <div class="desc-div"> <%= location.name %> </div>
  <% end %>
 <% else %>

  <%= link_to location_path(location) do %>
    <div class="desc-div no-img" > <%= location.name %> </div>
  <% end %>

<% end %>


<!-- height: 100, width: 133, crop: :fill %> </p>

app/views/locations/create.html.erb
<h1>Locations#create</h1>
<p>Find me in app/views/locations/create.html.erb</p>

app/views/locations/destroy.html.erb
<h1>Locations#destroy</h1>
<p>Find me in app/views/locations/destroy.html.erb</p>

app/views/locations/edit.html.erb
<h1>Locations#edit</h1>
<p>Find me in app/views/locations/edit.html.erb</p>

app/views/locations/index.html.erb
<h1 style="display:none"> Carte des lieux </h1>

<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
><div id='geocoder' class='geocoder'></div></div>


<%= link_to "+", new_location_path, id:'addlocationbutton' %>

<!-- 100vh ou 500px -->

app/views/locations/new.html.erb
<div class="nouvelemplacement">
  <h1>Signaler une décharge sauvage </h1>

  <p style="font-size: 16px; text-align: center"> <em> NB: veuillez autoriser votre position </em> </p>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/locations/show.html.erb
<div class="lieu">
  <h1><%= @location.name %> </h1>

    <% unless @location.photo.blank? %>
      <div class="backimg" style="background-image: linear-gradient(50deg, #FF512F10, #DD247610), url(<%= cl_image_path(@location.photo) %>);">
      </div>
    <% end %>


  <div class="bodylieu">
    <h2> Description </h2>

    <div id="i-have-a-tooltip" data-description="I'm a tooltip!">
      <% if !@location.description || @location.description.blank? %>
        <p> <em> Pas de description </em> </p>
      <% else %>
        <p> <%= @location.description %> </p>
      <% end %>
    </div>

    <h2> Type de déchets présents </h2>
    <div id="i-have-a-tooltip" data-description="I'm a tooltip!">
      <% if @location.garbage.empty? %>
        <p> <em> Aucun déchet indiqué </em> </p>
      <% else %>
      <ul>
        <% @location.garbage.each do |g| %>
          <li> <%= g %> </li>
        <% end %>
      </ul>
    <% end %>
    </div>

    <% if @location.event %>
      <%= link_to 'Rejoins la collecte !', event_path(@location.event), class: "btn center-block btn-lieu" %>
    <% else %>
      <p> Pas de collecte pour l'instant </p>
      <%= link_to 'Organiser une collecte', new_location_event_path(@location), class: "btn center-block btn-lieu" %>
    <% end %>
  </div>

</div>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/locations/zoom.html.erb
<h1> Emplacements à proximité de <%= @place %> </h1>

app/views/pages/home.html.erb
<body>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Quicksand');
  </style>
  <div class="banner">
    <h1>Marre de te promener dans les déchets ?</h1>
    <%= link_to 'Voir les décharges sauvages', locations_path, class: "btn cta hhome" %>
  </div>

  <div class="questcequegreenup">
    <h3>Green Up, c'est quoi ?</h3>
    <p class="justified">Tu te balades et tu vois un tas d'ordures. Ton réflexe : Green Up <br><br>
      Signale l'endroit où tu es sur la carte. Préviens les autres. Regroupez-vous pour le nettoyage.<br><br>C'est un petit pas pour l'homme et un grand pas pour l'environnement.</p>

  </div>

  <% texts = ["Un mouchoir en papier met 3 mois à se dégrader", "Un trognon de pomme met 5 mois à se dégrader", "Une carte téléphonique met 1000 ans à se dégrader", "Un filet de pêche met 600 ans à se dégrader", "Une brique de lait met 5 mois à se dégrader", "De l'huile de vidange met 15 ans à se dégrader", "Un papier de bonbon met 5 ans à se dégrader", "Un journal met 12 mois à se dégrader", "Un ticket de bus met un an à se dégrader"] %>

  <div class="video">
    <div class="desc">
      <h3> Le saviez-vous ? <br><br> <%= texts.sample %> </h3>
    </div>
  </div>


</body>

app/views/shared/_error_messages.html.erb
 <% if object.errors.any? %>
  <div id="error_explanation">
   <div class="alert alert-error">
     The form contains <%= pluralize(object.errors.count, "error") %>.
   </div>
  <ul>
   <% object.errors.full_messages.each do |msg| %>
    <li>* <%= msg %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/shared/_flashes.html.erb
<div class="flash">

  <% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>

</div>

app/views/shared/_footer.html.erb
<div style="clear:both;" class="footer">
  <p>© 2019 GreenUp | Tous droits réservés.</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg navbarhome">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to 'Voir la carte', locations_path %></li>
        <li><%= link_to 'Signaler une décharge sauvage;
        ', new_location_path %></li>
        <li><%= link_to 'Voir toutes les collectes', events_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Mon profil', user_path(current_user) %></li>
          <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li><%= link_to 'Se connecter', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand " do %>
    <%= image_tag "logo2.png", height: 50 %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="userprofilhtml">

<div class="container">

  <div class="row avatarbanner">
    <% if @user.avatar %>
      <div class="col-sm-6"> <%= image_tag @user.avatar, class:"profile-pict" %> </div>
    <% end %>
      <div class="card mes-points col-sm-6">
        <div class="pseudo">
          <strong> <%= @user.username %> </strong>
        </div>
        <div class="truc">
          Points : <%= @user_points %>
        </div>
        <!-- <p> Scores des users <%= @ordered_users_scores %> </p>
        <p> Point de l'user <%= @user_points %> </p> -->
        <p style="font-size: 16px !important; margin-top: 10px !important"> <i class="fa fa-star" aria-hidden="true"></i>
 Classement : <%= @rank %> / <%= @users.count %> </p>
      </div>
    </div>

    <div class="bio-user">
      <div class="card">
        <h3> Ma bio </h3>
        <p>
          <%= @user.bio  %>
        </p>
      </div>
    </div>

    <div class="infos-user">
      <div class="card mes-evenements">
        <div class="carte">
          <span><%= @user.events.count %></span>
          <% if @user.events.count < 2  %>
            <p>collecte créée</p>
          <% else %>
            <p>collectes créées</p>
          <% end %>

        </div>
      </div>


      <div class="card mes-participations">
        <div class="carte">
          <span><%= @user.event_participants.count  %></span>
          <% if @user.event_participants.count < 2 %>
            <p>participation</p>
          <% else %>
            <p>participations</p>
          <% end %>

        </div>
      </div>
    </div>

  </div>

</div>